[[headers]]
  for = "/elements/*.html"

  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"

[[headers]]
  for = "/icons/*.html"

  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"

[[headers]]
  for = "/api-examples/*.html"

  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"

[build]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF apps/web"
