[[headers]]
  for = "/elements/*.html"

  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"

[[headers]]
  for = "/api-examples/*.html"

  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"

[build]
  base = "./"
  ignore = "node ./netlify.ignore.js"
