[[headers]]
  for = "/elements/*.html"

  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"

[build]
  base = "apps/blog"
  ignore = "node apps/blog/netlify.ignore.js"
